version: "3.6"

services:
  client:
    image: kubix20/todoapp_client
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - public
    depends_on:
      - server

  server:
    image: kubix20/todoapp_server
    depends_on:
      - db
    networks:
      - private

  db:
    image: mongo:4.2.0
    volumes:
      - mongo-data:/data/db
    networks:
      - private

networks:
  public:
  private:

volumes:
  mongo-data: