version: "3.6"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
      
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: kubix20/app_vote
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis

  result:
    image: kubix20/app_result
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db

  worker:
    image: kubix20/app_worker
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis

networks:
  frontend:
  backend:

volumes:
  db-data:
